# This file was generated by GoReleaser. DO NOT EDIT.
cask "jaiscloud-aws" do
  version "0.1.0-alpha.2"

  on_macos do
    on_intel do
      sha256 "9083b3d710089b668e4a9c18d0ca50b6f45cfdd3c46bc31fcd8cb295aa3f6878"
      url "https://github.com/jaisrajms/jaiscloud/releases/download/v#{version}/jaiscloud-aws_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ef948cbf9093222a80b25bc12ab40b6a2138b7662d9ac1bb52d97396f51432c4"
      url "https://github.com/jaisrajms/jaiscloud/releases/download/v#{version}/jaiscloud-aws_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "67e641ed6191160bb4f924517c34d3f7f5bf6c7d4231147ccade1d3fa111aa81"
      url "https://github.com/jaisrajms/jaiscloud/releases/download/v#{version}/jaiscloud-aws_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "14e0302dead79e8fb47c26d4ad744ca0d1f5b8484c3c5d3720f793787dbc8f95"
      url "https://github.com/jaisrajms/jaiscloud/releases/download/v#{version}/jaiscloud-aws_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jaiscloud-aws"
  desc "Local AWS cloud emulator — AWS wire-protocol compatible"
  homepage "https://github.com/jaisrajms/jaiscloud"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jaiscloud-aws"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jaiscloud-aws"]
    end
  end

  # No zap stanza required

end
