# This file was generated by GoReleaser. DO NOT EDIT.
cask "jaiscloud-aws" do
  version "0.1.0-alpha.1"

  on_macos do
    on_intel do
      sha256 "388e764523afd6dc053515ff00e26c5411585ca10806dceb7004489887586bc4"
      url "https://github.com/jaisrajms/jaiscloud/releases/download/v#{version}/jaiscloud-aws_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6cb77e9292e32ed7d66859d1b2a5a16d14dbde91ada0367bbad6b22c66c2540d"
      url "https://github.com/jaisrajms/jaiscloud/releases/download/v#{version}/jaiscloud-aws_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "abf67aa31090e63e644bc3991741d0ad4e2421964498914820d476360f4ee485"
      url "https://github.com/jaisrajms/jaiscloud/releases/download/v#{version}/jaiscloud-aws_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "19a3f4e17f59f169a2d9a67d71281bdb42d49234d9228f6e0c50aa6361d557c2"
      url "https://github.com/jaisrajms/jaiscloud/releases/download/v#{version}/jaiscloud-aws_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jaiscloud-aws"
  desc "Local AWS cloud emulator — AWS wire-protocol compatible"
  homepage "https://github.com/jaisrajms/jaiscloud"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jaiscloud-aws"

  # No zap stanza required

end
