# This file was generated by GoReleaser. DO NOT EDIT.
cask "jaiscloud-aws" do
  version "0.1.0-alpha.1"

  on_macos do
    on_intel do
      sha256 "32917afa9472e58ba9eade403d17cde56586beaee5c972dfa3e0f200338eed78"
      url "https://github.com/jaisrajms/jaiscloud/releases/download/v#{version}/jaiscloud-aws_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "aeaa597e868de11ac1d012901a15b6ef80b8b363d512711bf23deefb98eed2d3"
      url "https://github.com/jaisrajms/jaiscloud/releases/download/v#{version}/jaiscloud-aws_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8ad6bd0d973fa464b537ad2bdc366767a7264986e10dcce2b67878cde71afad4"
      url "https://github.com/jaisrajms/jaiscloud/releases/download/v#{version}/jaiscloud-aws_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "eefe24464774aae1ba16ff989115c52f8b7bd0bd38f7343d5f15d982acffebed"
      url "https://github.com/jaisrajms/jaiscloud/releases/download/v#{version}/jaiscloud-aws_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jaiscloud-aws"
  desc "Local AWS cloud emulator — AWS wire-protocol compatible"
  homepage "https://github.com/jaisrajms/jaiscloud"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jaiscloud-aws"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jaiscloud-aws"]
    end
  end

  # No zap stanza required

end
