# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JaiscloudAws < Formula
  desc "Local AWS cloud emulator — AWS wire-protocol compatible"
  homepage "https://github.com/jaisrajms/jaiscloud"
  version "0.1.0-alpha.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaisrajms/jaiscloud/releases/download/v0.1.0-alpha.1/jaiscloud-aws_0.1.0-alpha.1_darwin_amd64.tar.gz"
      sha256 "302e529dcc29a72adccdc5561d4c76f6f9d77e843b32dcf3da69ac2691650430"

      define_method(:install) do
        bin.install "jaiscloud-aws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaisrajms/jaiscloud/releases/download/v0.1.0-alpha.1/jaiscloud-aws_0.1.0-alpha.1_darwin_arm64.tar.gz"
      sha256 "c614d3697f4881e3ad0b6ed41dfff8755c9d4ac573724eb760948df2e1035ee1"

      define_method(:install) do
        bin.install "jaiscloud-aws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaisrajms/jaiscloud/releases/download/v0.1.0-alpha.1/jaiscloud-aws_0.1.0-alpha.1_linux_amd64.tar.gz"
      sha256 "ce01fdd956c4c513a152fb3d293ef053ca611727c1b636eb33afaf113929986b"
      define_method(:install) do
        bin.install "jaiscloud-aws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaisrajms/jaiscloud/releases/download/v0.1.0-alpha.1/jaiscloud-aws_0.1.0-alpha.1_linux_arm64.tar.gz"
      sha256 "79a28b68993dd7248488330fa5e466af7f99b772587b9908219acd4989567ff3"
      define_method(:install) do
        bin.install "jaiscloud-aws"
      end
    end
  end
end
